apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test_documentation
  description: 'Documentation for test'
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: team-a
